import semantic.dp as dp

cache='dataset/corpus'

configs = [
    #pretrained models
    {
        "model":'glove',
        "pretrained":"pretrained",
        "vector_size":50
    },
    {
        "model":'glove',
        "pretrained":"pretrained",
        "vector_size":100
    },
    {
        "model":'glove',
        "pretrained":"pretrained",
        "vector_size":200
    },
    {
        "model":'glove',
        "pretrained":"pretrained",
        "vector_size":300
    },
    {
        "model":'fasttext',
        "pretrained":"pretrained",
    },
    {
        "model":'word2vec',
        "pretrained":"pretrained",
    },
    {
        "model":'sbert',
        "pretrained":"pretrained",
        "semantic_training":False
    },
    #baselines
    {
        "model":'string',
        "st":0
    },
    {
        "model":'levenshtein',
        "st":2
    },
    #Optimized
    {
        "model":'sbert',
        "pretrained":"pretrained_optimized",
        "semantic_training":False
    },
    {
        "model":'sbert',
        "pretrained":"pretrained_optimized",
        "semantic_training":True
    },
    {
        "model":'sbert',
        "pretrained":"pretrained",
        "semantic_training":True
    },
    {
        "model":'fasttext',
        "pretrained":"pretrained_optimized",
        "n_threads":32
    },
    #trained_from_scratch
    {
        "model":'glove',
        "window_size":7,
        "vector_size":194,
        "pretrained":"from_scratch",
        "n_threads":32
    },
    {
        "model":'fasttext',
        "window_size":7,
        "vector_size":194,
        "pretrained":"from_scratch",
        "n_threads":32
    },
    {
        "model":'word2vec',
        "window_size":7,
        "vector_size":194,
        "pretrained":"from_scratch",
        "n_threads":32
    },
    {
        "model":'sbert',
        "vector_size":192,
        "pretrained":"from_scratch",
        "semantic_training":True
    },
    {
        "model":"dpw",
        "n":3,
        "latent":True,
        "k":3,
        "c":dp.Cutoff.knee
    },
    {
        "model":"dpwc",
        "n":3,
        "latent":True,
        "k":2,
        "c":dp.Cutoff.knee,
        "kl":5
    }
]
